/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlignCenter: typeof import('./src/components/configPanel/AlignCenter.vue')['default']
    Attr: typeof import('./src/components/configPanel/Attr.vue')['default']
    AttrBorder: typeof import('./src/components/configPanel/AttrBorder.vue')['default']
    AttrColor: typeof import('./src/components/configPanel/AttrColor.vue')['default']
    AttrShadow: typeof import('./src/components/configPanel/AttrShadow.vue')['default']
    AttrText: typeof import('./src/components/configPanel/AttrText.vue')['default']
    ColorPanel: typeof import('./src/components/ColorPanel.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    Copy: typeof import('./src/components/configPanel/Copy.vue')['default']
    Del: typeof import('./src/components/configPanel/Del.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    Element: typeof import('./src/components/sidebar/Element.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Filter: typeof import('./src/components/configPanel/Filter.vue')['default']
    Layer: typeof import('./src/components/sidebar/Layer.vue')['default']
    Lock: typeof import('./src/components/configPanel/Lock.vue')['default']
    Logo: typeof import('./src/components/header/Logo.vue')['default']
    Material: typeof import('./src/components/sidebar/Material.vue')['default']
    MenuSwitch: typeof import('./src/components/MenuSwitch.vue')['default']
    PositionAndSize: typeof import('./src/components/configPanel/PositionAndSize.vue')['default']
    Save: typeof import('./src/components/header/Save.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Template: typeof import('./src/components/sidebar/Template.vue')['default']
    WorkspaceBgColor: typeof import('./src/components/configPanel/WorkspaceBgColor.vue')['default']
    WorkspaceSize: typeof import('./src/components/configPanel/WorkspaceSize.vue')['default']
    Zoom: typeof import('./src/components/Zoom.vue')['default']
  }
}
